[[main]]
  name = "Video"
  pageRef = "/video/"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "/tags/"
  weight = 40

[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 10


[[social]]
  name = "X"
  pre = "fab fa-twitter"
  url = "https://twitter.com/gusibix"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/gusibi/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30
